site_name: Coding With Beer
site_url: https://with.cupof.beer/
nav:
    - 'ç®€ä»‹': 
      - index.md
    - 'åŸºç¡€ç®—æ³•':
      - coding/basics/index.md
      - 'å»é‡': 'coding/basics/unique.md'
      - 'æ’åº': 'coding/basics/sorting.md'
      - 'äºŒåˆ†': 'coding/basics/half.md'
      - 'é«˜ç²¾åº¦': 'coding/basics/high-precision.md'
      - 'å‰ç¼€å’Œ': 'coding/basics/prefix-sum.md'
      - 'å·®åˆ†': 'coding/basics/diff-arr.md'
      - 'åŒæŒ‡é’ˆ': 'coding/basics/double-pointer.md'
      - 'äºŒè¿›åˆ¶': 'coding/basics/binary.md'
      - 'ç¦»æ•£åŒ–': 'coding/basics/discretization.md'
      - 'åŒºé—´åˆå¹¶': 'coding/basics/interval-unite.md'
    - 'æ•°æ®ç»“æ„':
        - 'æ¨¡æ‹Ÿé“¾è¡¨':
          - 'coding/data-structure/static-list/static-list-intro.md'
          - 'æ¨¡æ‹Ÿå•é“¾è¡¨': 'coding/data-structure/static-list/static-singlelist.md'
          - 'æ¨¡æ‹ŸåŒé“¾è¡¨': 'coding/data-structure/static-list/static-doublelist.md'


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
  # disqus: 'MTAyMC81NTY1Ni8zMjEyMw=='

copyright: Copy, right? ğŸ¤”

extra_javascript:
  - javascripts/extra.js
  - javascripts/config.js
  # - javascripts/busuanzi.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/JustLinton/

markdown_extensions:
  - toc:
      toc_depth: 3
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  # - attr_list
  # - def_list
  - pymdownx.highlight:
     linenums: true
     linenums_style: pymdownx.inline
  # - pymdownx.tasklist:
  #     clickable_checkbox: true
  #     custom_checkbox: true
  - pymdownx.superfences




theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  palette:
    scheme: nord
    # primary: whiteÂ¸Â¸Â¸Â¸
    accent: nord
  icon:
    logo: material/beer-outline
  features:
    - navigation.tabs
    - navigation.instant
    # - navigation.sections
    - navigation.expand
    - navigation.indexes
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  
  plugins:
    - search:
      lang:
          - en
          - ja
      separator: '[\s\-\.]+'
    # - search:
    #   lang:
    #     - en
    #     - ja
    #   separator: '[\s\-\.]+'
      # prebuild_index: true

