site_name: With Beer
site_url: https://with.cupof.beer/
nav:
    - Home: 
      - index.md
      - 'About': 'about.md'
    - Coding:
      - coding/index.md
      - 'æ’åº': 'coding/sorting.md'
      - 'äºŒåˆ†': 'coding/half.md'
      - 'é«˜ç²¾åº¦': 'coding/high-precision.md'
    - Mathematics:
      - mathematics/index.md
      # - 'about': 'mathematics/about.md'
      # - 'about2': 'mathematics/about2.md'
    - "Computer Structure":
      - computer-structure/index.md
      # - 'about': 'computer-structure/about.md'
      # - 'about2': 'computer-structure/about2.md'
    - "Data Structure":
      - data-structure/index.md
      # - 'about': 'data-structure/about.md'
      # - 'about2': 'data-structure/about2.md'
    - "Operating System":
      - operating-system/index.md
      # - 'about': 'operating-system/about.md'
      # - 'about2': 'operating-system/about2.md'
    - "Networks":
      - networks/index.md
      # - 'about': 'networks/about.md'
      # - 'about2': 'networks/about2.md'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
  # disqus: 'MTAyMC81NTY1Ni8zMjEyMw=='

copyright: Copy, right? ğŸ¤”

extra_javascript:
  - javascripts/extra.js
  - javascripts/config.js
  # - javascripts/busuanzi.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/JustLinton/

markdown_extensions:
  - toc:
      toc_depth: 3
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.highlight:
     linenums: true
     linenums_style: pymdownx.inline
  - pymdownx.superfences




theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  palette:
    scheme: nord
    # primary: whiteÂ¸Â¸Â¸Â¸
    accent: nord
  icon:
    logo: material/beer-outline
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  
  plugins:
    - search:
          lang:
            - en
            - ru
          prebuild_index: true

