site_name: Coding With Beer
site_url: https://with.cupof.beer/
nav:
    - 'ç®€ä»‹': 
      - index.md
    - 'åŸºç¡€ç®—æ³•':
      - 'å…³äºæœ¬ç« èŠ‚':
        - coding/basics/about/index.md
      - 'å»é‡': 
        - coding/basics/unique/index.md
        - 'vectorçš„å»é‡' : 'coding/basics/unique/unique-using-vector.md'
      - 'æ’åº': 
        - 'coding/basics/sorting/index.md'
        - 'å½’å¹¶æ’åº' : 'coding/basics/sorting/merge-sort.md'
        - 'å¿«é€Ÿæ’åº' : 'coding/basics/sorting/quick-sort.md'
      - 'äºŒåˆ†': 
        - 'coding/basics/binary-search/index.md'
        - 'æ•´æ•°äºŒåˆ†' : 'coding/basics/binary-search/integer-binary-search.md'
        - 'æµ®ç‚¹äºŒåˆ†' : 'coding/basics/binary-search/float-binary-search.md'
      - 'é«˜ç²¾åº¦': 
        - 'coding/basics/high-precision/index.md'
        - 'é«˜ç²¾åº¦åŠ æ³•' : 'coding/basics/high-precision/high-precision-plus.md'
        - 'é«˜ç²¾åº¦å‡æ³•' : 'coding/basics/high-precision/high-precision-sub.md'
        - 'é«˜ç²¾åº¦ä¹˜æ³•' : 'coding/basics/high-precision/high-precision-mul.md'
        - 'é«˜ç²¾åº¦é™¤æ³•' : 'coding/basics/high-precision/high-precision-div.md'
      - 'å‰ç¼€å’Œ':
        - 'coding/basics/prefix-sum/index.md'
        - 'ä¸€ç»´å‰ç¼€å’Œ' : 'coding/basics/prefix-sum/prefix-sum-dim1.md'
        - 'äºŒç»´å‰ç¼€å’Œ' : 'coding/basics/prefix-sum/prefix-sum-dim2.md' 
      - 'å·®åˆ†': 
        - 'coding/basics/diff-arr/index.md'
        - 'ä¸€ç»´å·®åˆ†' : 'coding/basics/diff-arr/diff-arr-dim1.md'
        - 'äºŒç»´å·®åˆ†' : 'coding/basics/diff-arr/diff-arr-dim2.md'
      - 'åŒæŒ‡é’ˆ': 
        - 'coding/basics/double-pointer/index.md'
      - 'äºŒè¿›åˆ¶': 
        - 'coding/basics/binary/index.md'
      - 'ç¦»æ•£åŒ–': 
        - 'coding/basics/discretization/index.md'
      - 'åŒºé—´åˆå¹¶': 
        - 'coding/basics/interval-unite/index.md'
    - 'æ•°æ®ç»“æ„':
        - 'å…³äºæœ¬ç« èŠ‚':
          - coding/data-structure/about/index.md
        - 'é™æ€é“¾è¡¨':
          - coding/data-structure/static-list/index.md
          - 'é™æ€å•é“¾è¡¨': 'coding/data-structure/static-list/static-singlelist.md'
          - 'é™æ€åŒé“¾è¡¨': 'coding/data-structure/static-list/static-doublelist.md'


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/linton_collin
      name: Linton Jiang on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/JustLinton
      name: Linton Jiang on Github
    - icon: fontawesome/brands/behance
      link: https://github.com/JustLinton
      name: Linton Jiang on Behance
  # disqus: 'MTAyMC81NTY1Ni8zMjEyMw=='

copyright: Copy, right? ğŸ¤”

extra_javascript:
  - javascripts/extra.js
  - javascripts/config.js
  # - javascripts/busuanzi.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/JustLinton/

markdown_extensions:
  - toc:
      toc_depth: 3
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  # - attr_list
  # - def_list
  - pymdownx.highlight:
     linenums: true
     linenums_style: pymdownx.inline
  # - pymdownx.tasklist:
  #     clickable_checkbox: true
  #     custom_checkbox: true
  - pymdownx.superfences




theme:
  name: material
  language: 'zh'
  custom_dir: overrides
  favicon: images/favicon.ico
  palette:
    - scheme: beer
      accent: beer
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: beer-dark 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # scheme: nord
    # primary: whiteÂ¸Â¸Â¸Â¸
    # accent: nord
  icon:
    logo: material/beer-outline
  features:
    - navigation.tabs
    - navigation.instant
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  
  plugins:
    - search:
      prebuild_index: true


